Practicum11 workshop
Justsvetoslavov/Object-oriented_programming_FMI_2021-2022 pull request #15
Opened 2022-05-19 07:57 UTC by nikola354

2022-05-19 08:08 UTC, Justsvetoslavov commented
Initial suggestion:
Split the files into 2 folders
- headers - all .h/.hpp files
- cpp - all .cpp files

2022-05-19 18:02 UTC, GeorgiTerziev02 requested changes
A lot of things can be simplified

2022-05-20 07:13 UTC, nikola354 commented on Sem. 11/Practicum/Car/cpp/Car.cpp
> +void Car::addTire(const Tire &tire, int count) {
Yes, because we don't get tires[] in the constructor with parameters

2022-05-20 07:14 UTC, nikola354 commented on Sem. 11/Practicum/Car/h/String.h
> +    void setName(const char *);
Took it directly from seminar 7 :D

2022-05-31 19:06 UTC, YavorAlexandrov approved these changes

2022-06-02 06:46 UTC, GeorgiTerziev02 approved these changes

2022-06-03 08:40 UTC, merged