Pr task teams
Justsvetoslavov/Object-oriented_programming_FMI_2021-2022 pull request #25
Opened 2022-06-12 19:23 UTC by plamena-ilieva

Книга с рецепти
Проект по ООП на екип 13 - Атанас Ников, Иван Дянков, Пламена Илиева

2022-06-13 09:36 UTC, atanasova07 commented on Additional/Teams/Team-13/src/cpp/RecipeBook.cpp
> +}
Debug error: abort() has been called when i=0 because in line 28 the index of recipes[i-1] is not valid. And as a result in Vector.hpp line 142 the function throw unhandled exception. So you can add check for index<0 in Vector.hpp

2022-06-13 09:50 UTC, atanasova07 reviewed
Additional checks 
Passing function parameters as a constant

2022-06-13 09:59 UTC, telinc1 requested changes
Като цяло е добре. Най-големият проблем е при `RecipeBook::addRecipe`, което не работи.

2022-06-13 09:59 UTC, telinc1 commented on Additional/Teams/Team-13/src/hpp/Recipe.h
> +	const size_t getDifficulty() const;
За не-скаларните типове по-добре върнете референции, за да не копирате цялата стойност.

2022-06-13 09:59 UTC, telinc1 commented on Additional/Teams/Team-13/src/hpp/Recipe.h
> +	virtual void determineDifficulty() = 0;
Мисля, че може доста да се подобри начинът, по който работи трудността.

За момента, трудността се запазва в базовия клас, но се управлява изцяло от наследниците, което създава проблеми. Най-малкото, че методи като `setDifficulty` са `public`, което позволява изцяло да се заобиколят правилата за определяне на трудността. По-съществено, `determineDifficulty` трябва да се извиква изрично в конструкторите на наследниците, т.е. те стават отговорни за инициализацията на базовия си клас. Друг проблем на тази система е, че трудността зависи от характеристиките на ястието, но те могат да бъдат променени след като ястието е създадено. Тъй като никъде не се извиква `determineDifficulty`, ще се получи несъответствие.

Според мен най-лесната алтернатива е следната. Махнете изцяло `difficulty` от базовия клас. После, сложете чисто виртуална `getDifficulty`, в която всяко ястие трябва "на момента" да изчисли трудността си и директно да я върне. Така хем изисквате всяко ястие да има трудност, хем изчезва тази особена зависимост между базовия клас и наследниците.

2022-06-13 09:59 UTC, telinc1 commented on Additional/Teams/Team-13/src/cpp/RecipeBook.cpp
> +    }
В много случаи този цикъл е безкраен (напр. когато няма рецепти) и почти веднага гърми.

2022-06-13 09:59 UTC, telinc1 commented on Additional/Teams/Team-13/src/cpp/RecipeBook.cpp
> +RecipeBook& RecipeBook::operator=(const RecipeBook& other){
Ако вече има рецепти, `free()` просто ги изтрива, но оставя изветрелите пойнтъри във вектора, а `copyFrom()` добавя нови пойнтъри след тях. В крайна сметка списъкът с рецепти ще е счупен. Някъде след като изтриете старите рецепти, но преди да добавите новите, трябва да изчистите вектора.

2022-06-13 10:30 UTC, atanasova07 reviewed
add constant

2022-06-13 10:30 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/Vector.hpp
> +    void deleteAt(size_t);
(const size_t) for all functions

2022-06-13 10:34 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/Vector.hpp
> +    T *newMemory = new T[capacity];
T* newMemory = new T[capacity*=2]

2022-06-13 10:38 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/Vector.hpp
> +}
it is better to remove line 130 and make the loop: for(int i = size; i > index; i--)
And add size++ after line 135

2022-06-13 10:41 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/Vector.hpp
> +}
remove line 122 and write data[size++]=element, because the index will increment after the assignment

2022-06-13 10:42 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/Vector.hpp
> +}
Add data=nullptr and make capacity = size = 0

2022-06-13 10:50 UTC, atanasova07 reviewed
passing parameter as a const variables

2022-06-13 10:50 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/RecipeBook.h
> +    int findAtId(int id) const;
findAtId(const int id)

2022-06-13 10:50 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/RecipeBook.h
> +    bool addRating(int rating, int id);
bool removeRecipe(const int id);
 bool addRating(const int rating, const int id);

2022-06-13 10:50 UTC, atanasova07 commented on Additional/Teams/Team-13/src/hpp/RecipeBook.h
> +    void printDifficulty(unsigned short difficulty) const;
void printDifficulty(const unsigned short difficulty) const;

2022-06-13 10:52 UTC, atanasova07 commented on Additional/Teams/Team-13/src/cpp/RecipeBook.cpp
> +    recipes.push_back(recipe);
it is better to clone the recipe
 recipes.push_back(recipe->clone());

2022-06-13 11:16 UTC, atanasova07 reviewed
There is no need to create 7 variables, which will be used only once throughout the code. Instead, you could use the names of the commands themselves in the if-else statements like this: compare("add", command)

2022-06-13 11:16 UTC, atanasova07 commented on Additional/Teams/Team-13/src/cpp/RecipeBookMain.cpp
> +	if (compare(addCommand, command)) {
Remove the variables and write if statements like this: compare("add",command)

2022-06-13 11:16 UTC, atanasova07 commented on Additional/Teams/Team-13/src/cpp/RecipeBookMain.cpp
> +	if (compare(openCommand, command)) {
Same thing here

2022-06-13 17:56 UTC, telinc1 commented on Additional/Teams/Team-13/src/cpp/RecipeBook.cpp
> +    recipes.deleteAt(index);
Memory leak: махате пойнтъра, но не триете паметта, към която сочи.

2022-06-19 13:18 UTC, atanasova07 commented
@Justsvetoslavov  we are ready for your review :)

2022-06-21 15:51 UTC, atanasova07 approved these changes

2022-06-21 17:05 UTC, telinc1 approved these changes

2022-06-22 08:53 UTC, merged