Team 3
Justsvetoslavov/Object-oriented_programming_FMI_2021-2022 pull request #30
Opened 2022-06-12 21:46 UTC by tswetti

2022-06-13 06:49 UTC, GeorgiTerziev02 requested changes

2022-06-13 06:49 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/h/Organism.h
> +	StringC getConservationLevelStr() const;
const StringC&

2022-06-13 06:49 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/StringC.cpp
> +	if (strlen(str) == 0)
In case str has length > 0, you will read the length 2 times on line 146 and on 154
on line 145 simply write size = strlen(str), then you will skip some lines afterwards

2022-06-13 06:49 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/h/RedBook.h
> +	Organism** list;
You can use the included vector here...

2022-06-13 06:49 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/Organism.cpp
> +	for (int i = 0; i < 7; i++)
if you used enum, you would have skipped these checks

2022-06-13 06:49 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/RedBook.cpp
> +		delete tmp;
Do not delete

2022-06-13 06:49 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/RedBook.cpp
> +/*void RedBook::printSpecific(char* type) const {
The logic behind these commented lines looks good to have the typeToStr(), so that you would skip the next three methods printFlora, printFauna, printFungi, but you should improve the checks on the type in the if clauses.

2022-06-16 09:22 UTC, GeorgiTerziev02 requested changes

2022-06-16 09:22 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/h/Vector.hpp
> +	T& At(const size_t) const;
You don't need this method when you have the operator[] which is doing the same

2022-06-16 09:22 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/Organism.cpp
> +		if (habitats.At(i) == remHabitat)
operator[]

2022-06-16 09:22 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/RedBook.cpp
> +	return list[index]->clone();
I don't think you need a clone of the Organism.
This is prone to memory leak.
Just return the current pointer

2022-06-16 10:22 UTC, nikola354 commented on Additional/Teams/Team 3/cpp/RedBook.cpp
> +	return list[index]->clone();
return the current pointer but constant

2022-06-19 11:40 UTC, tswetti commented on Additional/Teams/Team 3/h/Organism.h
> +#include <iostream>
moved

2022-06-19 14:25 UTC, GeorgiTerziev02 approved these changes
Looks good

2022-06-19 14:25 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/StringC.cpp
> +	const char* str = input.getString();
Advise: Overload operator[] of the string

2022-06-19 14:25 UTC, GeorgiTerziev02 commented on Additional/Teams/Team 3/cpp/RedBook.cpp
> +	int index;
Advise: This code can look cleaner like this
if(......) 
     return ......

return strToInt(input)

2022-06-21 10:39 UTC, Justsvetoslavov reviewed
In documentation do not include Rule of 3/Big 4/Rule of 5.
Do not include private methods.
Not necessary to explicitly point virtual functions, setter&getters etc.

Documentation should serve as a guide for the user.

2022-06-21 10:40 UTC, Justsvetoslavov commented on Additional/Teams/Team 3/h/StringC.h
> +class StringC
would suggest name to be MyString or just String, if there isn't a specific reason for the "C".

2022-06-21 10:40 UTC, Justsvetoslavov commented on Additional/Teams/Team 3/h/Organism.h
> +		leastConcern = 0,
by default enum list starts from 0.

2022-06-21 10:41 UTC, Justsvetoslavov commented on Additional/Teams/Team 3/h/Organism.h
> +	double lifeSpan;
swap lines 27 and 28. Do you understand why ?

2022-06-21 10:42 UTC, Justsvetoslavov commented on Additional/Teams/Team 3/h/Flora.h
> +
remove empty line.

2022-06-21 10:42 UTC, Justsvetoslavov commented on Additional/Teams/Team 3/h/Fauna.h
> +class Fauna : public Organism
remove unnecessary empty lines.

2022-06-21 10:42 UTC, Justsvetoslavov commented on Additional/Teams/Team 3/cpp/StringC.cpp
> +	{
brackets aren't required.

2022-06-28 12:39 UTC, merged