Commit team 5
Justsvetoslavov/Object-oriented_programming_FMI_2021-2022 pull request #31
Opened 2022-06-12 22:12 UTC by DaniellaGeorgieva

2022-06-15 09:00 UTC, nikola354 commented on Additional/Teams/Team№5/src/cpp/Shop.cpp
> +	address = "";
you can remove these lines. the default constructor of String makes the same thing

2022-06-15 09:01 UTC, nikola354 commented on Additional/Teams/Team№5/src/h/Shop.h
> +	String getAddress() const;
const String& ?

2022-06-15 09:01 UTC, nikola354 commented on Additional/Teams/Team№5/src/h/Shop.h
> +	String getAddress() const;
const String& ?

2022-06-15 09:03 UTC, nikola354 commented on Additional/Teams/Team№5/src/h/Shop.h
> +	void diplayAddDialog();
typo

2022-06-15 09:06 UTC, nikola354 commented on Additional/Teams/Team№5/src/cpp/Shop.cpp
> +	size_t countToAdd;
check if the price is positive number

2022-06-15 10:46 UTC, GeorgiTerziev02 requested changes

2022-06-15 10:46 UTC, GeorgiTerziev02 commented on Additional/Teams/Team№5/src/h/ClothingContainer.h
> +	double getPrice(size_t);
const function

2022-06-15 10:46 UTC, GeorgiTerziev02 commented on Additional/Teams/Team№5/src/h/ClothingContainer.h
> +	void ListSoldItems();
List functions should be const

2022-06-15 10:46 UTC, GeorgiTerziev02 commented on Additional/Teams/Team№5/src/h/ClothingContainer.h
> +	void ExportSoldLog();
again const function

2022-06-15 10:46 UTC, GeorgiTerziev02 commented on Additional/Teams/Team№5/src/cpp/ClothingContainer.cpp
> +	double* tempLogPrice = new double[capacity * 2];
Why are you resizing everything in one method?
Example: Line 69
You are removing an item, but you call resize later so you are resizing the container and the log, when you only needed to resize the log

2022-06-15 10:46 UTC, GeorgiTerziev02 commented on Additional/Teams/Team№5/src/h/ClothingContainer.h
> +	void ExportSoldLog();
The above 3 methods should be const

2022-06-15 10:46 UTC, GeorgiTerziev02 commented on Additional/Teams/Team№5/src/cpp/Shop.cpp
> +			//function from container
//do something or delete the if

2022-06-15 17:30 UTC, GeorgiTerziev02 commented on Additional/Teams/Team№5/src/h/ClothingContainer.h
> +	void ListSoldItems();
+ function names should be camelCase - starting with lower letter

2022-06-17 10:17 UTC, GeorgiTerziev02 requested changes
Looks fine but it needs some minor fixes

2022-06-17 18:44 UTC, nikola354 approved these changes

2022-06-18 07:24 UTC, GeorgiTerziev02 approved these changes

2022-06-20 21:58 UTC, Justsvetoslavov reviewed
Diagram is incorrect.

Clothing shop has a "Clothing Container" (composition) and clothing container consists of cloths(clothingItem) , again composition.

If you are struggling to understand this, ping me to discuss it.

2022-06-20 21:59 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingItem.cpp
> +{}
move to line 3.

2022-06-20 21:59 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingItem.cpp
> +{}
move to line 5

2022-06-20 22:06 UTC, Justsvetoslavov requested changes

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingItem.cpp
> +
remove empty lines.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingItem.cpp
> +		return;
returns are unnecessary ,as well as brackets, statements will be 1 liners.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingItem.cpp
> +	if (size == "XS" || size == "xs")
remove brackets , 1 liners.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingItem.cpp
> +	case ClothingItem::Size::UNKNOWN:
could be considered as the default.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/Couture.cpp
> +{}
move to line 3

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingContainer.cpp
> +	{
remove brackets.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingContainer.cpp
> +	{
remove brackets.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingContainer.cpp
> +	{
remove brackets.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingContainer.cpp
> +	{
remove brackets.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingContainer.cpp
> +	{
remove brackets.

2022-06-20 22:06 UTC, Justsvetoslavov commented on Additional/Teams/Team№5/src/cpp/ClothingContainer.cpp
> +bool ClothingContainer::deleteClothingItem(size_t index) const
adjust 1 liners.

2022-06-28 12:40 UTC, merged