Team 14 commit
Justsvetoslavov/Object-oriented_programming_FMI_2021-2022 pull request #32
Opened 2022-06-13 09:52 UTC by Bozhidar02

Team 14 commit
9MI0600121
0MI0600022
4MI0600030

2022-06-13 11:50 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/Vector.h
> +    MyVector() {
You need Rule of four because you use dynamic memory.
And it is better  const int default_capacity = 2 to be a global variable. So in functions if you need the default value you can assign it to cap (cap=default_capacity)

2022-06-13 11:52 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/Vector.h
> +}
Create private free() function and use it here

2022-06-13 12:06 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/String.h
> +        String(const char* data);
Again you need rule of four( default constructor, copy assignment operator), also copyFrom and free functions

2022-06-13 12:08 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/String.h
> +        char* getText() const;
const char* getText() const;

2022-06-13 12:17 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/Weapon.h
> +	virtual double use() override;
don't need to write virtual, only override

2022-06-13 12:33 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/String.h
> +        }
it is unnecessary to write this->

2022-06-13 13:07 UTC, atanasova07 commented on Additional/Teams/Team14/src/cpp/Player.cpp
> +	delete weapon;
delete[] weapon

2022-06-13 13:08 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/Warrior.h
> +	virtual Player* clone() const override;
don't need to write virtual

2022-06-13 14:32 UTC, atanasova07 commented on Additional/Teams/Team14/src/h/String.h
> +#pragma once
You already have #pragma once, delete the second one

2022-06-13 14:44 UTC, telinc1 requested changes
Като структура и функционалност не виждам проблеми. На доста места има memory leak-ове, като един от случаите е доста нетривиален за поправка.

2022-06-13 14:44 UTC, telinc1 commented on Additional/Teams/Team14/src/h/Item.h
> +	~Item();
`virtual`

2022-06-13 14:44 UTC, telinc1 commented on Additional/Teams/Team14/src/cpp/Warrior.cpp
> +	strength = WARRIOR_START_STRG;
Параметърът `strength` не се използва за нищо (ред 13 само го презаписва). Може би сте искали `this->strength = strength`?

2022-06-13 14:44 UTC, telinc1 commented on Additional/Teams/Team14/src/h/Sword.h
> +	Sword(const Sword&);
В случаите, когато класът няма собствена динамична памет (този е такъв), служебният копиращ конструктор върши работа.

2022-06-13 14:44 UTC, telinc1 commented on Additional/Teams/Team14/src/cpp/String.cpp
> +    }
Не изтрива `data`.

2022-06-13 14:44 UTC, telinc1 commented on Additional/Teams/Team14/src/cpp/Arena.cpp
> +}
Никъде не изтривате `buffer` и `arr`.

2022-06-13 14:44 UTC, telinc1 commented on Additional/Teams/Team14/src/cpp/Player.cpp
> +}
Никъде не се изтрива `inventory`. Само един `delete inventory;` не е достатъчен, за да се оправи, защото след края на битка някои от пойнтърите в инвентара на загубилия директно се местят при спечелилия.

Ако е от полза: вижте резултатите от Valgrind [в сегашния вид на кода](https://dpaste.org/5dZTH) и [фойерверките](https://dpaste.org/Ft7Bf), които се получават, ако тук просто изтрием `inventory` (честно казано, във фойерверките и аз не мога да се ориентирам).

2022-06-13 14:44 UTC, telinc1 commented on Additional/Teams/Team14/src/cpp/Inventory.cpp
> +}
В целия клас `size` и `capacity` се използват в обратен смисъл на този, който обикновено използваме. Заради това тук трябва да триете/копирате до `capacity`, иначе класът ще работи с неинициализирана памет.

2022-06-19 09:40 UTC, telinc1 approved these changes

2022-06-19 11:37 UTC, atanasova07 approved these changes

2022-06-19 13:17 UTC, atanasova07 commented
@Justsvetoslavov  we are ready for your review :)

2022-06-28 12:42 UTC, merged