Team 12 project
Justsvetoslavov/Object-oriented_programming_FMI_2021-2022 pull request #35
Opened 2022-06-14 14:38 UTC by Plamena02

2022-06-14 14:58 UTC, atanasova07 commented on Additional/Teams/Team12/src/h/vector.h
> +	T popAt(const size_t);
It is better to be T& popAt(const size_t)
Correct it also in line 145

2022-06-14 15:10 UTC, atanasova07 commented on Additional/Teams/Team12/src/h/Vehicle.h
> +	Vehicle(size_t, size_t, MyString, double, double);
It is good idea MyString to be const MyString& ---> Vehicle(size_t, size_t, const MyString&, double, double);

2022-06-14 15:18 UTC, atanasova07 commented on Additional/Teams/Team12/src/cpp/Vehicle.cpp
> +	this -> battery = ((batteryRange - km) * 100) / batteryRange;
You can go without this->, because there is not another variable battery

2022-06-14 15:46 UTC, telinc1 requested changes

2022-06-14 15:46 UTC, telinc1 commented on Additional/Teams/Team12/src/cpp/Driver.cpp
> +Driver::Driver(MyString name, size_t identityNumber, size_t age, driverLicense type) : name(name), identityNumber(identityNumber), age(age), license(type) {}
Change the parameter to `const MyString& name` or use `std::move` in the initializer list.

2022-06-14 15:46 UTC, telinc1 commented on Additional/Teams/Team12/src/cpp/Vehicle.cpp
> +Vehicle::Vehicle(size_t DriverIdentityNumber,size_t vehicleID, MyString model, double batteryRange, double chargingRate) :
Unused parameter `model`.

2022-06-14 15:46 UTC, telinc1 commented on Additional/Teams/Team12/src/cpp/Transport.cpp
> +        Transport::vehicles.pushBack(new IntercityBus(idDriver, idVehicle, model, range, rate, start, end, sH, sM, fH, fM, bH, bM, breakMinutes, breakStop));
Memory leak: an `IntercityBus` is created, cloned in `Container::pushBack`, then the original is ignored (also on lines 186, 205, 219).

2022-06-14 15:46 UTC, telinc1 commented on Additional/Teams/Team12/src/cpp/Transport.cpp
> +    Transport::vehicles.popAt(index);
Memory leak: `popAt` returns the pointer that was removed from the `Container`, but this pointer is never `delete`d.

2022-06-14 15:50 UTC, atanasova07 commented on Additional/Teams/Team12/src/h/CityBus.h
> +	CityBus(size_t, size_t, MyString, double, double, MyString, MyString, size_t, size_t, size_t, size_t, size_t);
Change MyString to const MyString& in all constructors (not only in this file)

2022-06-14 18:44 UTC, atanasova07 commented on Additional/Teams/Team12/src/cpp/InterCityBus.cpp
> +	listOfStops.pushAt(breakStop, listOfStops.getSize() - 2);
If you want breakStop to be in the middle you have to write "-1" instead of "-2" (because in this way the start destination becomes stop destination)

2022-06-14 18:59 UTC, atanasova07 commented on Additional/Teams/Team12/src/cpp/ElectricBus.cpp
> +	if (!(sHour < 24 && fHour < 24 && sMin < 60 && fMin < 60 && sHour * 60 + sMin > fHour * 60 + fMin)) throw std::invalid_argument("Invalid time period");
It should be (...sHour * 60 + sMin **<** fHour * 60 + fMin) because in other way it throw invalid time and don't set the time.

2022-06-14 19:30 UTC, atanasova07 commented on Additional/Teams/Team12/src/cpp/Transport.cpp
> +        cin >> idVehicle;
Add  new line:   cout << "Id of the driver: ";

2022-06-14 19:35 UTC, atanasova07 commented on Additional/Teams/Team12/src/cpp/Transport.cpp
> +        cout << "Model of the bus: ";
Add new line: cout << "Id of the driver: ";
line 213 should be "Model of the scooter: "
line 197: "Model of the car: "
line 166: "Model of the cityBus: "

2022-06-14 19:42 UTC, atanasova07 commented on Additional/Teams/Team12/src/cpp/Transport.cpp
> +    cin >> input;
add this (cout << endl << "> ";)after line 91 to look better

2022-06-16 10:17 UTC, telinc1 approved these changes

2022-06-17 18:34 UTC, atanasova07 approved these changes

2022-06-19 13:16 UTC, atanasova07 commented
@Justsvetoslavov  we are ready for your review :)

2022-06-28 12:41 UTC, merged