Nvector Solution by Nikolay Nikolaev
Justsvetoslavov/Object-oriented_programming_FMI_2021-2022 pull request #9
Opened 2022-04-15 07:42 UTC by SupPanda9

Решение на задача Nvector от sem07 от Николай Николаев - 6 група.

2022-04-15 21:46 UTC, YavorAlexandrov requested changes

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/Cartesian.h
> +	Cartesian2D& operator=(const Cartesian2D&);
Big four shouldn't be defined in this class as there is no unhandled dynamic memory.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	try {
Exceptions are thrown as information to the person who is using this function. There is no point catching the exception you are throwing as no one will find out this exception was thrown.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	try {
Same comment for the exception throwing.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +double Nvector::getCoordinate(size_t index) const
This function is actually the [] operator. You should define it instead.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +void Nvector::setCoordinate(double num, size_t index)
Again, this is the [] operator but as a non-const function.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	try {
fix exception throwing

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	try {
fix exception throwing

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	try {
fix exception throwing

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	vector.coordinates = new double[vector.size];
Here you can redirect vector.coordinates pointer to buffer and then make buffer nullptr. This way copying can be avoided.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +const Nvector operator+(const Nvector& first, const Nvector& second)
No need to return const Nvector as it restricts unnecessary the user of this function. Since we are returning a copy of the object it can be non-const.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +const Nvector operator-(const Nvector& first, const Nvector& second)
No need for const return type.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +const Nvector operator*(const Nvector& vector, const double num)
No need for const return type.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +const Nvector operator*(const double num, const Nvector& vector)
No need for const return type.

2022-04-15 21:46 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/Cartesian.cpp
> +Cartesian2D::Cartesian2D(const Nvector first, const Nvector second)
Arguments should be const references.

2022-04-15 22:14 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/Cartesian.h
> +	Nvector getVectorByCoordinates(const Nvector&);
Function should be constant.

2022-04-15 22:14 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/Cartesian.h
> +	Nvector getCoordinatesByVector(const Nvector&);
Function should be constant.

2022-04-15 22:14 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.h
> +	bool isCollinear(const Nvector&);
Function should be constant.

2022-04-15 22:15 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.h
> +	bool isPerpendicular(const Nvector&);
Function should be constant.

2022-04-15 22:15 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.h
> +	double dotProduct(const Nvector&);
Function should be constant.

2022-04-17 18:23 UTC, GeorgiTerziev02 reviewed
Use ctrl k+d to format your code

2022-04-17 18:23 UTC, GeorgiTerziev02 commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	coordinates = new double[size];
new double [size] ()
shorter syntax for initializing array of zeros

2022-04-17 18:23 UTC, GeorgiTerziev02 commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	if (index > size - 1) {
index>=size

2022-04-17 18:23 UTC, GeorgiTerziev02 commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	double ratio = coordinates[0] / other.coordinates[0];
What if other.coordinates[0] is 0?

2022-04-17 18:23 UTC, GeorgiTerziev02 commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +		currRatio = coordinates[i] / other.coordinates[i];
What if other.coordinates[i] is 0?

2022-04-17 18:23 UTC, GeorgiTerziev02 commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	else return false;
You can just return dotProduct(other) == 0

2022-04-17 18:23 UTC, GeorgiTerziev02 commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +	if (index > size - 1) {
index>=size

2022-04-19 13:38 UTC, YavorAlexandrov requested changes

2022-04-19 13:38 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.h
> +	double& setCoordinate(size_t); //value, index
This function should be
`double& operator[](size_t);`

2022-04-19 13:38 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +		if (currRatio - ratio<0 || currRatio - ratio>EPSILON) {
this can be rewritten as 
`currRatio - ratio != 0`

2022-04-19 13:38 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +		std::cout<<"Different sizes!"<<std::endl;
It's better to throw an exception here or at least to write on the **cerr** output instead of the standard output to log the error.

2022-04-19 13:38 UTC, YavorAlexandrov commented on Sem. 07/Practicum/Nvector/NVector.cpp
> +		std::cout<<"Different sizes!"<<std::endl;
Same comment for the exception.

2022-04-24 14:06 UTC, Justsvetoslavov commented
Final review before merge: @YavorAlexandrov , @GeorgiTerziev02

2022-04-25 18:21 UTC, YavorAlexandrov approved these changes

2022-04-25 19:31 UTC, GeorgiTerziev02 approved these changes

2022-04-26 07:49 UTC, merged